// Подборка иконок Hugeicons, из которой владелец выбирает иконку этапа на странице Flow. Имя — экспорт пакета без
// суффикса Icon: оно хранится в этапе, поэтому переименовывать нельзя — этап с пропавшим именем показывает иконку по виду.
import type { IconSvgElement } from "@hugeicons/react";
import {
  Agreement01Icon,
  AiBrain01Icon,
  AiChat01Icon,
  AiIdeaIcon,
  AiMagicIcon,
  AlarmClockIcon,
  Album01Icon,
  AnalysisTextLinkIcon,
  Analytics01Icon,
  Analytics02Icon,
  ArchiveIcon,
  ArrowDataTransferHorizontalIcon,
  Attachment01Icon,
  Award01Icon,
  BeakerIcon,
  Book02Icon,
  BookOpen01Icon,
  Bookmark02Icon,
  BotIcon,
  BrainIcon,
  BubbleChatIcon,
  BubbleChatQuestionIcon,
  Bug01Icon,
  BulbIcon,
  BulbChargingIcon,
  CalculatorIcon,
  Calendar03Icon,
  CalendarCheckIn01Icon,
  Camera01Icon,
  Certificate01Icon,
  ChartBarLineIcon,
  ChartHistogramIcon,
  ChartLineData01Icon,
  Chatting01Icon,
  CheckListIcon,
  CheckmarkBadge01Icon,
  CheckmarkCircle02Icon,
  CheckmarkSquare02Icon,
  ClipboardIcon,
  ClipboardListIcon,
  Clock01Icon,
  CloudIcon,
  CloudDownloadIcon,
  CloudServerIcon,
  CloudUploadIcon,
  CodeIcon,
  CodeCircleIcon,
  CodeFolderIcon,
  CodeSquareIcon,
  ColorPickerIcon,
  CommandLineIcon,
  Comment01Icon,
  CompassIcon,
  ComputerIcon,
  ComputerTerminal01Icon,
  Configuration01Icon,
  ContractsIcon,
  CrownIcon,
  CubeIcon,
  DashboardSquare01Icon,
  DatabaseIcon,
  Delete02Icon,
  DiamondIcon,
  DocumentCodeIcon,
  DocumentValidationIcon,
  Download01Icon,
  EarthIcon,
  Edit02Icon,
  EyeIcon,
  File01Icon,
  FileAddIcon,
  FileCodeIcon,
  FileEditIcon,
  FileSearchIcon,
  FileValidationIcon,
  Files01Icon,
  FilterIcon,
  FilterHorizontalIcon,
  FireIcon,
  Flag01Icon,
  Flag02Icon,
  FlashIcon,
  FlowConnectionIcon,
  Flowchart01Icon,
  Folder01Icon,
  FolderOpenIcon,
  FolderSearchIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitCompareIcon,
  GitForkIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GithubIcon,
  GlobeIcon,
  GridIcon,
  HammerIcon,
  HandshakeIcon,
  HashIcon,
  HeadingIcon,
  HierarchyIcon,
  HourglassIcon,
  Idea01Icon,
  Image01Icon,
  InboxIcon,
  InspectCodeIcon,
  Invoice01Icon,
  Key01Icon,
  LaptopIcon,
  Layers01Icon,
  Layers02Icon,
  Layout01Icon,
  LayoutGridIcon,
  LeftToRightListBulletIcon,
  LibraryIcon,
  LicenseIcon,
  LicenseDraftIcon,
  Link01Icon,
  ListSettingIcon,
  ListViewIcon,
  LockIcon,
  LockKeyIcon,
  MagicWand01Icon,
  Mail01Icon,
  Medal01Icon,
  Megaphone01Icon,
  MergeIcon,
  Message01Icon,
  MessageMultiple01Icon,
  MessageQuestionIcon,
  Mic01Icon,
  MicroscopeIcon,
  Money01Icon,
  MonitorIcon,
  Navigation03Icon,
  Note01Icon,
  NoteEditIcon,
  NotebookIcon,
  Notebook01Icon,
  Notification01Icon,
  PackageIcon,
  PackageDeliveredIcon,
  PaintBrush01Icon,
  PaletteIcon,
  ParagraphIcon,
  Pen01Icon,
  PenTool01Icon,
  PenTool03Icon,
  PencilIcon,
  PencilEdit01Icon,
  PencilEdit02Icon,
  PieChartIcon,
  PlayIcon,
  PlayCircleIcon,
  Presentation01Icon,
  PresentationBarChart01Icon,
  ProjectorIcon,
  PuzzleIcon,
  RefreshIcon,
  RepeatIcon,
  Robot01Icon,
  RocketIcon,
  Rocket01Icon,
  Route01Icon,
  ScaleIcon,
  ScanIcon,
  ScanEyeIcon,
  Search01Icon,
  SearchList01Icon,
  SecurityIcon,
  SecurityCheckIcon,
  SendIcon,
  SentIcon,
  ServerIcon,
  ServerStack01Icon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  SignatureIcon,
  SignpostIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  Sorting01Icon,
  SourceCodeIcon,
  SparklesIcon,
  SplitIcon,
  StarIcon,
  StopCircleIcon,
  Tag01Icon,
  TagsIcon,
  Target01Icon,
  Task01Icon,
  Task02Icon,
  TaskDone01Icon,
  TaskEdit01Icon,
  TestTubeIcon,
  TextFontIcon,
  ThumbsUpIcon,
  TickDouble02Icon,
  Time01Icon,
  Timer01Icon,
  ToolsIcon,
  TranslateIcon,
  TrashIcon,
  TrophyIcon,
  Upload01Icon,
  UserIcon,
  UserCheck01Icon,
  UserGroupIcon,
  UserMultipleIcon,
  UserSearch01Icon,
  UsersIcon,
  Video01Icon,
  ViewIcon,
  WorkflowIcon,
  WorkflowCircle01Icon,
  Wrench01Icon,
  ZapIcon,
  ZoomInAreaIcon,
} from "@hugeicons/core-free-icons";

/** Иконки подборки по имени, в порядке показа в выборе. */
export const STAGE_ICONS: ReadonlyMap<string, IconSvgElement> = new Map<string, IconSvgElement>([
  ["Agreement01", Agreement01Icon],
  ["AiBrain01", AiBrain01Icon],
  ["AiChat01", AiChat01Icon],
  ["AiIdea", AiIdeaIcon],
  ["AiMagic", AiMagicIcon],
  ["AlarmClock", AlarmClockIcon],
  ["Album01", Album01Icon],
  ["AnalysisTextLink", AnalysisTextLinkIcon],
  ["Analytics01", Analytics01Icon],
  ["Analytics02", Analytics02Icon],
  ["Archive", ArchiveIcon],
  ["ArrowDataTransferHorizontal", ArrowDataTransferHorizontalIcon],
  ["Attachment01", Attachment01Icon],
  ["Award01", Award01Icon],
  ["Beaker", BeakerIcon],
  ["Book02", Book02Icon],
  ["BookOpen01", BookOpen01Icon],
  ["Bookmark02", Bookmark02Icon],
  ["Bot", BotIcon],
  ["Brain", BrainIcon],
  ["BubbleChat", BubbleChatIcon],
  ["BubbleChatQuestion", BubbleChatQuestionIcon],
  ["Bug01", Bug01Icon],
  ["Bulb", BulbIcon],
  ["BulbCharging", BulbChargingIcon],
  ["Calculator", CalculatorIcon],
  ["Calendar03", Calendar03Icon],
  ["CalendarCheckIn01", CalendarCheckIn01Icon],
  ["Camera01", Camera01Icon],
  ["Certificate01", Certificate01Icon],
  ["ChartBarLine", ChartBarLineIcon],
  ["ChartHistogram", ChartHistogramIcon],
  ["ChartLineData01", ChartLineData01Icon],
  ["Chatting01", Chatting01Icon],
  ["CheckList", CheckListIcon],
  ["CheckmarkBadge01", CheckmarkBadge01Icon],
  ["CheckmarkCircle02", CheckmarkCircle02Icon],
  ["CheckmarkSquare02", CheckmarkSquare02Icon],
  ["Clipboard", ClipboardIcon],
  ["ClipboardList", ClipboardListIcon],
  ["Clock01", Clock01Icon],
  ["Cloud", CloudIcon],
  ["CloudDownload", CloudDownloadIcon],
  ["CloudServer", CloudServerIcon],
  ["CloudUpload", CloudUploadIcon],
  ["Code", CodeIcon],
  ["CodeCircle", CodeCircleIcon],
  ["CodeFolder", CodeFolderIcon],
  ["CodeSquare", CodeSquareIcon],
  ["ColorPicker", ColorPickerIcon],
  ["CommandLine", CommandLineIcon],
  ["Comment01", Comment01Icon],
  ["Compass", CompassIcon],
  ["Computer", ComputerIcon],
  ["ComputerTerminal01", ComputerTerminal01Icon],
  ["Configuration01", Configuration01Icon],
  ["Contracts", ContractsIcon],
  ["Crown", CrownIcon],
  ["Cube", CubeIcon],
  ["DashboardSquare01", DashboardSquare01Icon],
  ["Database", DatabaseIcon],
  ["Delete02", Delete02Icon],
  ["Diamond", DiamondIcon],
  ["DocumentCode", DocumentCodeIcon],
  ["DocumentValidation", DocumentValidationIcon],
  ["Download01", Download01Icon],
  ["Earth", EarthIcon],
  ["Edit02", Edit02Icon],
  ["Eye", EyeIcon],
  ["File01", File01Icon],
  ["FileAdd", FileAddIcon],
  ["FileCode", FileCodeIcon],
  ["FileEdit", FileEditIcon],
  ["FileSearch", FileSearchIcon],
  ["FileValidation", FileValidationIcon],
  ["Files01", Files01Icon],
  ["Filter", FilterIcon],
  ["FilterHorizontal", FilterHorizontalIcon],
  ["Fire", FireIcon],
  ["Flag01", Flag01Icon],
  ["Flag02", Flag02Icon],
  ["Flash", FlashIcon],
  ["FlowConnection", FlowConnectionIcon],
  ["Flowchart01", Flowchart01Icon],
  ["Folder01", Folder01Icon],
  ["FolderOpen", FolderOpenIcon],
  ["FolderSearch", FolderSearchIcon],
  ["GitBranch", GitBranchIcon],
  ["GitCommit", GitCommitIcon],
  ["GitCompare", GitCompareIcon],
  ["GitFork", GitForkIcon],
  ["GitMerge", GitMergeIcon],
  ["GitPullRequest", GitPullRequestIcon],
  ["Github", GithubIcon],
  ["Globe", GlobeIcon],
  ["Grid", GridIcon],
  ["Hammer", HammerIcon],
  ["Handshake", HandshakeIcon],
  ["Hash", HashIcon],
  ["Heading", HeadingIcon],
  ["Hierarchy", HierarchyIcon],
  ["Hourglass", HourglassIcon],
  ["Idea01", Idea01Icon],
  ["Image01", Image01Icon],
  ["Inbox", InboxIcon],
  ["InspectCode", InspectCodeIcon],
  ["Invoice01", Invoice01Icon],
  ["Key01", Key01Icon],
  ["Laptop", LaptopIcon],
  ["Layers01", Layers01Icon],
  ["Layers02", Layers02Icon],
  ["Layout01", Layout01Icon],
  ["LayoutGrid", LayoutGridIcon],
  ["LeftToRightListBullet", LeftToRightListBulletIcon],
  ["Library", LibraryIcon],
  ["License", LicenseIcon],
  ["LicenseDraft", LicenseDraftIcon],
  ["Link01", Link01Icon],
  ["ListSetting", ListSettingIcon],
  ["ListView", ListViewIcon],
  ["Lock", LockIcon],
  ["LockKey", LockKeyIcon],
  ["MagicWand01", MagicWand01Icon],
  ["Mail01", Mail01Icon],
  ["Medal01", Medal01Icon],
  ["Megaphone01", Megaphone01Icon],
  ["Merge", MergeIcon],
  ["Message01", Message01Icon],
  ["MessageMultiple01", MessageMultiple01Icon],
  ["MessageQuestion", MessageQuestionIcon],
  ["Mic01", Mic01Icon],
  ["Microscope", MicroscopeIcon],
  ["Money01", Money01Icon],
  ["Monitor", MonitorIcon],
  ["Navigation03", Navigation03Icon],
  ["Note01", Note01Icon],
  ["NoteEdit", NoteEditIcon],
  ["Notebook", NotebookIcon],
  ["Notebook01", Notebook01Icon],
  ["Notification01", Notification01Icon],
  ["Package", PackageIcon],
  ["PackageDelivered", PackageDeliveredIcon],
  ["PaintBrush01", PaintBrush01Icon],
  ["Palette", PaletteIcon],
  ["Paragraph", ParagraphIcon],
  ["Pen01", Pen01Icon],
  ["PenTool01", PenTool01Icon],
  ["PenTool03", PenTool03Icon],
  ["Pencil", PencilIcon],
  ["PencilEdit01", PencilEdit01Icon],
  ["PencilEdit02", PencilEdit02Icon],
  ["PieChart", PieChartIcon],
  ["Play", PlayIcon],
  ["PlayCircle", PlayCircleIcon],
  ["Presentation01", Presentation01Icon],
  ["PresentationBarChart01", PresentationBarChart01Icon],
  ["Projector", ProjectorIcon],
  ["Puzzle", PuzzleIcon],
  ["Refresh", RefreshIcon],
  ["Repeat", RepeatIcon],
  ["Robot01", Robot01Icon],
  ["Rocket", RocketIcon],
  ["Rocket01", Rocket01Icon],
  ["Route01", Route01Icon],
  ["Scale", ScaleIcon],
  ["Scan", ScanIcon],
  ["ScanEye", ScanEyeIcon],
  ["Search01", Search01Icon],
  ["SearchList01", SearchList01Icon],
  ["Security", SecurityIcon],
  ["SecurityCheck", SecurityCheckIcon],
  ["Send", SendIcon],
  ["Sent", SentIcon],
  ["Server", ServerIcon],
  ["ServerStack01", ServerStack01Icon],
  ["Settings01", Settings01Icon],
  ["Share01", Share01Icon],
  ["Shield01", Shield01Icon],
  ["Signature", SignatureIcon],
  ["Signpost", SignpostIcon],
  ["SlidersHorizontal", SlidersHorizontalIcon],
  ["Smartphone", SmartphoneIcon],
  ["Sorting01", Sorting01Icon],
  ["SourceCode", SourceCodeIcon],
  ["Sparkles", SparklesIcon],
  ["Split", SplitIcon],
  ["Star", StarIcon],
  ["StopCircle", StopCircleIcon],
  ["Tag01", Tag01Icon],
  ["Tags", TagsIcon],
  ["Target01", Target01Icon],
  ["Task01", Task01Icon],
  ["Task02", Task02Icon],
  ["TaskDone01", TaskDone01Icon],
  ["TaskEdit01", TaskEdit01Icon],
  ["TestTube", TestTubeIcon],
  ["TextFont", TextFontIcon],
  ["ThumbsUp", ThumbsUpIcon],
  ["TickDouble02", TickDouble02Icon],
  ["Time01", Time01Icon],
  ["Timer01", Timer01Icon],
  ["Tools", ToolsIcon],
  ["Translate", TranslateIcon],
  ["Trash", TrashIcon],
  ["Trophy", TrophyIcon],
  ["Upload01", Upload01Icon],
  ["User", UserIcon],
  ["UserCheck01", UserCheck01Icon],
  ["UserGroup", UserGroupIcon],
  ["UserMultiple", UserMultipleIcon],
  ["UserSearch01", UserSearch01Icon],
  ["Users", UsersIcon],
  ["Video01", Video01Icon],
  ["View", ViewIcon],
  ["Workflow", WorkflowIcon],
  ["WorkflowCircle01", WorkflowCircle01Icon],
  ["Wrench01", Wrench01Icon],
  ["Zap", ZapIcon],
  ["ZoomInArea", ZoomInAreaIcon],
]);
