export {
  CLOSED,
  HUG,
  dragHeight,
  heightFromStorage,
  heightToStorage,
  pinnedByUser,
  pluginSettingsPath,
  present,
  release,
  step,
  type ItemKey,
  type Presented,
  type PresentStep,
  type WindowEvent,
  type WindowHeight,
  type WindowState,
} from "./core";
export {
  HOVER_LEAVE_MS,
  dismissFooterWindow,
  presentFooterWindow,
  registerFooterWindow,
  releaseFooterWindow,
  resetFooterWindowsForTests,
  setOpenOnHover,
  togglePin,
  useHoldHeight,
  useOpenOnHover,
  usePinned,
  withFooterWindow,
  type DisclosureController,
  type FooterItem,
  type FooterItemEntry,
} from "./footer-window";
export { FooterWindow, FooterWindowButton, FooterWindowHeader, type FooterWindowAction, type FooterWindowProps } from "./window-view";
