// Falls back to a session's own working directory when the primary
// session-id -> BB-thread-identity match (threads-timeline-service.ts's
// buildSessionToBbThreadMap) comes up empty. That primary path only ever
// sees a thread's LATEST `thread/identity` event and only threads still
// inside the scanned window — it misses a thread that changed its
// provider session mid-life (compaction/resume), one whose environment
// outlived it after deletion, and any "unmanaged" environment that never
// ran inside a `.bb/`-prefixed copy at all. `cwd` is the session's own
// ground truth for where it actually ran; these functions turn that back
// into a BB project two different ways depending on how the environment
// was provisioned, plus a last-resort human-readable guess when neither
// applies. Pure and total — no I/O, no bb.sdk; the service layer supplies
// already-fetched environment/project data.
const BB_MANAGED_PATH_RE = /\/\.bb\/(?:worktrees|personal-workspaces)\/([^/]+)(?:\/|$)/;

/**
 * The bb-managed environment id a session ran under, parsed from its own
 * `cwd` — present only for a `.bb/worktrees/<envId>/...` or
 * `.bb/personal-workspaces/<envId>/...` copy. Null for a session that ran
 * directly in a project's own checkout (an "unmanaged" environment) or
 * outside BB's workspace layout entirely — see {@link projectIdForCwd} for
 * that case.
 */
export function bbManagedEnvironmentId(cwd: string | null): string | null {
  if (cwd === null) return null;
  return cwd.match(BB_MANAGED_PATH_RE)?.[1] ?? null;
}

/** A BB project's own checkout root, as registered (`bb.sdk.projects.list()`'s `sources[].path`) — one entry per source. */
export interface ProjectPath {
  id: string;
  path: string;
}

/**
 * The registered BB project whose own checkout root contains `cwd` — for a
 * session that ran directly in a project's primary checkout (no
 * `.bb/worktrees/` copy layer at all) rather than a managed environment.
 * Longest-path match wins, so a project nested inside another project's
 * checkout doesn't grab sessions that belong to the nested one. Null when
 * `cwd` isn't under any registered project's own path — including every
 * `.bb/`-managed cwd, since those never equal a project's raw checkout
 * path (see {@link bbManagedEnvironmentId} for that case instead).
 */
export function projectIdForCwd(cwd: string | null, projects: readonly ProjectPath[]): string | null {
  if (cwd === null) return null;
  let best: ProjectPath | null = null;
  for (const p of projects) {
    if (cwd === p.path || cwd.startsWith(`${p.path}/`)) {
      if (best === null || p.path.length > best.path.length) best = p;
    }
  }
  return best?.id ?? null;
}

// Claude Code's OWN native worktree feature (`git worktree` under
// `.claude/worktrees/<auto-generated-slug>`) — unrelated to BB's
// `.bb/worktrees/<envId>`, and with no BB-side record to look up at all.
// Its auto-generated slug (and any package subdirectory nested inside it,
// e.g. `.../worktrees/<slug>/md-editor`) makes a poor project guess; the
// real project is the directory the worktree was created FROM, one level
// up from `.claude`.
const CLAUDE_NATIVE_WORKTREE_RE = /\/\.claude\/worktrees\/[^/]+(?:\/.*)?$/;

// `.bb/worktrees/<envId>/<projectDirName>/...` or
// `.bb/personal-workspaces/<envId>/<projectDirName>/...` — reached only when
// the environment lookup itself failed (see enrichBbProjects's tier 2:
// project deleted, or the record itself gone). The segment right after the
// env id is the project's own checkout directory name; anything deeper
// (a package subdirectory, a generated branch-name leaf) is not.
const BB_MANAGED_PROJECT_DIR_RE = /\/\.bb\/(?:worktrees|personal-workspaces)\/[^/]+\/([^/]+)/;

/**
 * Best-effort guess at "what was this", for a session matching no BB
 * project at all. Not shown as a project slice by itself — see {@link
 * fallbackProjectName}, which is the only caller and decides whether this
 * guess is trustworthy enough to merge into a real project's spend.
 *
 * Reads `cwd` outside-in: strips a Claude-native worktree tail first (its
 * slug isn't a project name), then prefers the directory named right after
 * a bb-managed env id when that pattern matches, else the path's own last
 * segment (closest to what a human calls the checkout, and immune to a
 * project name that itself contains hyphens). Falls back to the raw
 * transcript-directory slug's last hyphen-separated segment
 * (`-Users-e0068-Documents-Projects-Petrograd` -> "Petrograd") only when
 * `cwd` is unavailable. Never returns an empty string — an all-separator
 * input reads back as the input itself, unguessed.
 */
export function guessedProjectLabel(cwd: string | null, rawProjectSlug: string): string {
  if (cwd !== null) {
    const withoutNativeWorktree = cwd.replace(CLAUDE_NATIVE_WORKTREE_RE, "");
    const bbManagedProjectDir = withoutNativeWorktree.match(BB_MANAGED_PROJECT_DIR_RE)?.[1];
    if (bbManagedProjectDir) return bbManagedProjectDir;
    const lastSegment = withoutNativeWorktree
      .split("/")
      .filter((s) => s.length > 0)
      .at(-1);
    if (lastSegment) return lastSegment;
  }
  const fromSlug = rawProjectSlug
    .split("-")
    .filter((s) => s.length > 0)
    .at(-1);
  return fromSlug ?? rawProjectSlug;
}

/**
 * The shared bucket for a thread whose project genuinely can't be pinned
 * down — none of enrichBbProjects' three tiers matched, and (see {@link
 * fallbackProjectName}) its cwd-guessed name doesn't match any registered
 * project either. One bucket rather than one pseudo-project per guessed
 * directory name: see memory/decisions/usage-analytics-unlinked-merge-by-exact-name.md
 * for why a dozen one-off directory names cluttered the project picker more
 * than a single catch-all costs.
 */
export const UNKNOWN_PROJECT_LABEL = "Unknown Project";

/**
 * The bbProjectName for a thread none of enrichBbProjects' three tiers
 * could place. Merges into an already-registered BB project's own slice
 * when {@link guessedProjectLabel} happens to match that project's name
 * exactly (full string equality only — a fuzzy match risks silently
 * folding an unrelated same-ish-named checkout's spend into the wrong
 * project's budget); otherwise the thread lands in the shared {@link
 * UNKNOWN_PROJECT_LABEL} bucket instead of minting its own pseudo-project.
 * See memory/decisions/usage-analytics-unlinked-merge-by-exact-name.md.
 */
export function fallbackProjectName(cwd: string | null, rawProjectSlug: string, knownProjectNames: ReadonlySet<string>): string {
  const guessed = guessedProjectLabel(cwd, rawProjectSlug);
  return knownProjectNames.has(guessed) ? guessed : UNKNOWN_PROJECT_LABEL;
}
